// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Fri Mar 13 00:08:17 2020

ROM_READER_V2 ROM_READER_V2_inst
(
	.TRIGGER_IN(TRIGGER_IN_sig) ,	// input  TRIGGER_IN_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RESET(RESET_sig) ,	// input  RESET_sig
	.READ_ENA(READ_ENA_sig) ,	// output  READ_ENA_sig
	.ROM_ADDR(ROM_ADDR_sig) ,	// output [9:0] ROM_ADDR_sig
	.SOP(SOP_sig) ,	// output  SOP_sig
	.EOP(EOP_sig) 	// output  EOP_sig
);

